export const orders = {}
export const products = {
  "Red tomatoes": {"id": "Red tomatoes", "full": "Fresh tomatoes, red color.", "unit": "kg", "price": 4.7, "balance": 20, "type": "vegetables" },
  "Yellow tomatoes": {"id": "Yellow tomatoes", "full": "Fresh tomatoes, yellow color.", "unit": "kg", "price": 4.7, "balance": 7, "type": "vegetables" },
  "Black tomatoes": {"id": "Black tomatoes", "full": "Fresh tomatoes, black color.", "unit": "kg", "price": 6.2, "balance": 12, "type": "vegetables" },
  "Zuchinni green": {"id": "Zuchinni green", "full": "Fresh zuchinni, green color.", "unit": "kg", "price": 4.1, "balance": 6, "type": "vegetables" },
  "Zuchinni yellow": {"id": "Zuchinni yellow", "full": "Fresh zuchinni, yellow color.", "unit": "kg", "price": 4, "balance": 11, "type": "vegetables" },
  "Arugula": {"id": "Arugula", "full": "Fresh arugula.", "unit": "kg", "price": 15, "balance": 2, "type": "vegetables" },
  "Broccoli": {"id": "Broccoli", "full": "Fresh broccoli.", "unit": "kg", "price": 5.3, "balance": 5.2, "type": "vegetables" },
  "Coriander": {"id": "Coriander", "full": "Fresh coriander.", "unit": "kg", "price": 18, "balance": 1.45, "type": "vegetables" },
  "Daikon": {"id": "Daikon", "full": "Fresh daikon.", "unit": "kg", "price": 6.6, "balance": 2.85, "type": "vegetables" },
  "Bok choi": {"id": "Bok choi", "full": "Fresh bok choi.", "unit": "kg", "price": 23, "balance": 6, "type": "vegetables" },
  "Cocktail potatoes": {"id": "Cocktail potatoes", "full": "", "unit": "kg", "price": 3.6, "balance": 23, "type": "vegetables" },
  "Dill": {"id": "Dill", "full": "Fresh dill.", "unit": "kg", "price": 34.2, "balance": 2.5, "type": "vegetables" },
  "Basil": {"id": "Basil", "full": "Fresh basil..", "unit": "g", "price": 0.046, "balance": 521.8, "type": "herbs" },
  "Celery": {"id": "Celery", "full": "Fresh celery.", "unit": "g", "price": 0.039, "balance": 521.1, "type": "herbs" },
  "Watercress": {"id": "Watercress", "full": "Fresh watercress.", "unit": "g", "price": 0.054, "balance": 520.64, "type": "herbs" },
  "Mint": {"id": "Mint", "full": "Fresh mint.", "unit": "g", "price": 0.034, "balance": 523.1, "type": "herbs" },
  "Nasturtium": {"id": "Nasturtium", "full": "Fresh nasturtium.", "unit": "g", "price": 0.062, "balance": 521.1, "type": "herbs" },
  "Chives": {"id": "Chives", "full": "Fresh chives.", "unit": "g", "price": 0.033, "balance": 52.9, "type": "herbs" },
  "Button": {"id": "Button", "full": "Button mushrooms.", "unit": "kg", "price": 6.1, "balance": 4.3, "type": "mushrooms" },
  "Field": {"id": "Field", "full": "Field mushrooms.", "unit": "kg", "price": 21, "balance": 1.3, "type": "mushrooms" },
  "Enoki": {"id": "Enoki", "full": "Enoki mushrooms.", "unit": "kg", "price": 33, "balance": 3.3, "type": "mushrooms" },
  "Bread": {"id": "Bread", "full": "", "unit": "pts", "price": 3, "balance": 12, "type": "" },
  "Milk": {"id": "Milk", "full": "", "unit": "L", "price": 3.1, "balance": 9, "type": "" },
  "Eggs": {"id": "Eggs", "full": "", "unit": "pts", "price": 0.3, "balance": 82, "type": "" },
}
